#!/bin/bash
# usage: ./makesite [site_name]

export LC_CTYPE=C
export LANG=C

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 path_to_original_folder"
    exit 1
fi

original_folder="$1"
path_curtent="/var/www/zhangle"

# remove old current
if [ -d "$path_curtent" ]; then
    echo "Removing existing current folder..."
    rm -rf "$path_curtent"
fi

folder_enzh="${path_curtent}/enzh_site"
folder_zh="${path_curtent}/zh_site"
folder_en="${path_curtent}/en_site"

mkdir -p "${path_curtent}"

# copy files
cp -r "$original_folder" "$folder_enzh"
cp -r "$original_folder" "$folder_zh"
cp -r "$original_folder" "$folder_en"

# delete common file
rm "$folder_zh/index.html"
rm "$folder_en/index.html"

# move to new location from /cn
mv "$folder_zh/cn/"* "$folder_zh/"
rm -r "$folder_zh/cn/"

# move to new location from /en
mv "$folder_en/en/"* "$folder_en/"
rm -r "$folder_en/en/"

# replace path
find "$folder_zh/en" -type f -name '*.html' -exec sed -i 's/\/cn\//\//g' {} +
find "$folder_zh" -type f -name 'sitemap*.xml' -exec sed -i 's/https:\/\//http:\/\//g' {} +
find "$folder_zh" -type f -name 'sitemap*.xml' -exec sed -i 's/\/cn\//\//g' {} +
find "$folder_zh" -type f -name 'sitemap*.xml' -exec sed -i 's/www\.zhang-le\.com/www\.xn--fjqs32b\.cn/g' {} +

# replace path
find "$folder_en/cn" -type f -name '*.html' -exec sed -i 's/\/en\//\//g' {} +
find "$folder_en" -type f -name 'sitemap*.xml' -exec sed -i 's/\/en\//\//g' {} +
find "$folder_en" -type f -name 'sitemap*.xml' -exec sed -i 's/www\.zhang-le\.com/www\.zhangle\.ca/g' {} +

echo "Done"
