#!/bin/bash

BACKUP_DIR="/var/www/backup/zhangle"
TARGET_DIR="/var/www/zhangle"

LATEST_BACKUP=$(ls -td $BACKUP_DIR/backup_* | head -1)

if [ -z "$LATEST_BACKUP" ]; then
    echo "There is no backup"
    exit 1
fi

echo "Latest backup: $LATEST_BACKUP"

echo "Start Rollback..."
rsync -av --delete $LATEST_BACKUP/ $TARGET_DIR

if [ $? -eq 0 ]; then
    echo "Rollback Done"
    echo "Delete the latest backup $LATEST_BACKUP"
    rm -rf "$LATEST_BACKUP"
else
    echo "Rollback Failed, No chnages."
fi
