#!/bin/bash

repo_name=$1

# Get the current date and time in the format 'old_year_month_day_hour_min_second'
current_date=$(date +old_%Y_%m_%d_%H_%M_%S)

if [ -f "../../cloud" ]; then
    echo "REMOTE"
    
    # Step 1: Rename ../html if it exists
    if [ -d "../../html" ]; then
        mv "../../html" "../../$current_date"
    fi

    # Step 2: Copy the provided repo to ../html
    if [ -d "$repo_name" ]; then
        cp -r "$repo_name" "../../html"
    else
        echo "The repo '${repo_name}' doesn't exist!"
        exit 1
    fi
else
    echo "LOCALHOST"

    # Step 1: Rename ../html if it exists
    if [ -d "../../localhost/html" ]; then
        mv "../../localhost/html" "../../localhost/$current_date"
    fi

    # Step 2: Copy the provided repo to ../html
    if [ -d "$repo_name" ]; then
        cp -r "$repo_name" "../../localhost/html"
    else
        echo "The repo '${repo_name}' doesn't exist!"
        exit 1
    fi
fi

echo "Task completed!"
