//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZhangLe.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Experiences {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Experiences() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZhangLe.Resources.Experiences", typeof(Experiences).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/visual_arts/w0_0.jpg.
        /// </summary>
        public static string Exp1BackgroundImage {
            get {
                return ResourceManager.GetString("Exp1BackgroundImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photography is a technique that uses light. I have worked as a commercial photographer, capturing images of large commercial events. I also founded a photography club with friends in high school and organized several large club events in the form of photography lectures. During this period, I received many awards from the school. Personally, I am particularly interested in classical photography..
        /// </summary>
        public static string Exp1Description {
            get {
                return ResourceManager.GetString("Exp1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/visual_arts/w3_0.jpg.
        /// </summary>
        public static string Exp1MainImage {
            get {
                return ResourceManager.GetString("Exp1MainImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Exp1Project1Description {
            get {
                return ResourceManager.GetString("Exp1Project1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Exp1Project1Image {
            get {
                return ResourceManager.GetString("Exp1Project1Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Exp1Project1Link {
            get {
                return ResourceManager.GetString("Exp1Project1Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Exp1Project1Name {
            get {
                return ResourceManager.GetString("Exp1Project1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Exp1Project1Type {
            get {
                return ResourceManager.GetString("Exp1Project1Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The eye should learn to listen before it looks..
        /// </summary>
        public static string Exp1Quote {
            get {
                return ResourceManager.GetString("Exp1Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robert Frank.
        /// </summary>
        public static string Exp1QuoteAuthor {
            get {
                return ResourceManager.GetString("Exp1QuoteAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercial Photography - Dilireba Event.
        /// </summary>
        public static string Exp1Section1Image1Caption {
            get {
                return ResourceManager.GetString("Exp1Section1Image1Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/visual_arts/w1_0.jpg.
        /// </summary>
        public static string Exp1Section1Image1Src {
            get {
                return ResourceManager.GetString("Exp1Section1Image1Src", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blueprint Photo of a Building.
        /// </summary>
        public static string Exp1Section1Image2Caption {
            get {
                return ResourceManager.GetString("Exp1Section1Image2Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/visual_arts/w1_1.jpg.
        /// </summary>
        public static string Exp1Section1Image2Src {
            get {
                return ResourceManager.GetString("Exp1Section1Image2Src", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Exp1Section1QuoteAuthor {
            get {
                return ResourceManager.GetString("Exp1Section1QuoteAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Exp1Section1QuoteContent {
            get {
                return ResourceManager.GetString("Exp1Section1QuoteContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Exp1Section1QuoteDescription {
            get {
                return ResourceManager.GetString("Exp1Section1QuoteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing Video.
        /// </summary>
        public static string Exp1Section2Image1Caption {
            get {
                return ResourceManager.GetString("Exp1Section2Image1Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/visual_arts/w2_0.jpg.
        /// </summary>
        public static string Exp1Section2Image1Src {
            get {
                return ResourceManager.GetString("Exp1Section2Image1Src", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the High School Film.
        /// </summary>
        public static string Exp1Section2Image2Caption {
            get {
                return ResourceManager.GetString("Exp1Section2Image2Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/visual_arts/w2_1.jpg.
        /// </summary>
        public static string Exp1Section2Image2Src {
            get {
                return ResourceManager.GetString("Exp1Section2Image2Src", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vsevolod Pudovkin.
        /// </summary>
        public static string Exp1Section2QuoteAuthor {
            get {
                return ResourceManager.GetString("Exp1Section2QuoteAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The foundation of film art is editing..
        /// </summary>
        public static string Exp1Section2QuoteContent {
            get {
                return ResourceManager.GetString("Exp1Section2QuoteContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the photography club, not only Visual Arts activities are conducted, but also video recording. And we completed several groups of microfilm shooting and post-production during high school..
        /// </summary>
        public static string Exp1Section2QuoteDescription {
            get {
                return ResourceManager.GetString("Exp1Section2QuoteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Arts.
        /// </summary>
        public static string Exp1Title {
            get {
                return ResourceManager.GetString("Exp1Title", resourceCulture);
            }
        }
    }
}
