//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZhangLe.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomePage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomePage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZhangLe.Resources.HomePage", typeof(HomePage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third year Honour Physics Co-op Students in the University of Waterloo. Studying in physics major with computing minor. Co-Founder of VirtualPHY..
        /// </summary>
        public static string AboutDescription {
            get {
                return ResourceManager.GetString("AboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best works of the Science Fair | 2018.
        /// </summary>
        public static string Award1 {
            get {
                return ResourceManager.GetString("Award1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Club leader on Campus | 2018.
        /// </summary>
        public static string Award2 {
            get {
                return ResourceManager.GetString("Award2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Robotic Competition industrial design award | 2018.
        /// </summary>
        public static string Award3 {
            get {
                return ResourceManager.GetString("Award3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese Micro Film Festival Best Editing Award | 2018.
        /// </summary>
        public static string Award4 {
            get {
                return ResourceManager.GetString("Award4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le Zhang&apos;s Personal Website.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experiences.
        /// </summary>
        public static string Experiences {
            get {
                return ResourceManager.GetString("Experiences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High school is graduated from Henan Experimental High School, one of the top high schools in Henan Province, China, where he served as vice president of the high school Visual Arts club, audio engineer and event planner for the event operations team, and engineer and mechanical designer for the robotics team. And excelled in these positions. Successfully organized several large school events and won an industrial design award from General Motor in a robotics competition..
        /// </summary>
        public static string HighschoolExperience {
            get {
                return ResourceManager.GetString("HighschoolExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interests and Awards.
        /// </summary>
        public static string InterestsAndAwards {
            get {
                return ResourceManager.GetString("InterestsAndAwards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume Download.
        /// </summary>
        public static string ResumeDownload {
            get {
                return ResourceManager.GetString("ResumeDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to my personal website. I&apos;m Zhang, Le. Honours Physics student in the University of Waterloo, Interested in quantum physics and IoT..
        /// </summary>
        public static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
